### ISSUE TITLE
Make block compatible with Elemental 4

### ISSUE THREAD

**Issue by NightJar** [edgarindustries/silverstripe-elemental-map#1]
This looks great! It would be neat to see it work out of the box with the newest (next ATM) version of Elemental though - for this I think all that's needed is

```php
private static $inline_editable = false;
```
on `MapBlock.php` :)

**Comment by edlinklater** [comment]
Fixed in 0e58f069d6a6ca4098f19acc08350e456d454c0b, thanks!
