### ISSUE TITLE
Possible to add mapbox styles?

### ISSUE THREAD

**Issue by ghost** [edgarindustries/silverstripe-elemental-map#5]
Is it possible to add mapbox generated styles to the map block? Thanks

**Comment by edlinklater** [comment]
@CapicheDesign Currently Leaflet uses Mapbox Classic so it won't work with styles created in the new Mapbox Studio. My intention is to support choosing between Leaflet or `mapbox-gl-js`, the latter will allow use of Mapbox Studio custom styles.
